name: Auto Sync Resume

on:
  push:
    paths:
      - "resume.pdf"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout resume repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run sync script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python update_resume.py
